[versions]
android-gradle-plugin = "8.7.2"
apollo = "4.1.0"
appcompat = "1.7.0"
coil = "3.0.4"
constraintlayout = "2.2.0"
core = "1.15.0"
coroutines = "1.9.0"
draglistview = "1.7.3"
fragment = "1.8.5"
glide = "4.16.0"
glide-webpdecoder = "2.6.4.16.0"
hilt = "2.52"
hilt-extension-compiler = "1.2.0"
hilt-work = "1.2.0"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.26"
lifecycle = "2.8.7"
material = "1.12.0"
media3 = "1.5.0"
navigation = "2.8.4"
okhttp = "5.0.0-alpha.14"
okio = "3.9.1"
paging = "3.3.4"
preference = "1.2.1"
retrofit = "2.11.0"
room = "2.6.1"
serialization = "1.7.3"
swiperefreshlayout = "1.1.0"
webkit = "1.12.1"
work = "2.10.0"

[libraries]
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
draglistview = { module = "com.github.woxthebox:draglistview", version.ref = "draglistview" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glide-okhttp = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
glide-webpdecoder = { module = "com.github.zjupure:webpdecoder", version.ref = "glide-webpdecoder" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-extension-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-extension-compiler" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }

