[versions]
activity = "1.11.0"
android-gradle-plugin = "8.13.0"
apollo = "4.3.3"
appcompat = "1.7.1"
coil = "3.3.0"
conscrypt = "2.5.3"
constraintlayout = "2.2.1"
coordinatorlayout = "1.3.0"
core = "1.17.0"
coroutines = "1.10.2"
cronet = "119.6045.31"
customview = "1.2.0"
fragment = "1.8.9"
glide = "4.16.0"
glide-webpdecoder = "2.7.4.16.0"
hilt = "2.57.1"
hilt-extensions = "1.3.0"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.3"
lifecycle = "2.9.3"
material = "1.13.0"
media3 = "1.8.0"
navigation = "2.9.4"
okhttp = "5.1.0"
okio = "3.16.0"
paging = "3.3.6"
preference = "1.2.1"
recyclerview = "1.4.0"
room = "2.8.0"
serialization = "1.9.0"
swiperefreshlayout = "1.1.0"
viewpager2 = "1.1.0"
webkit = "1.14.0"
work = "2.10.4"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
apollo-api = { module = "com.apollographql.apollo:apollo-api", version.ref = "apollo" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
conscrypt = { module = "org.conscrypt:conscrypt-android", version.ref = "conscrypt" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
cronet-api = { module = "org.chromium.net:cronet-api", version.ref = "cronet" }
customview = { module = "androidx.customview:customview", version.ref = "customview" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glide-okhttp = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
glide-webpdecoder = { module = "com.github.zjupure:webpdecoder", version.ref = "glide-webpdecoder" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-extension-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-extensions" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-extensions" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }

